"""Utility functions for loading and inspecting the VisionAid landmark feature dataset.

Dataset overview
----------------
The primary dataset consumed by the ML pipeline is a pre-computed CSV file located at:

    data/processed/landmark_features.csv

This CSV is generated by the feature-extraction stage of the pipeline
(FaceShapeExperiment.build_feature_table).  Each row corresponds to one face image
that was *successfully* processed — images where no face could be detected, or where
landmark fitting failed, are silently dropped.

How to generate the CSV from scratch
-------------------------------------
1. Download the faceshape dataset from GitHub::

       git clone https://github.com/dsmlr/faceshape data/external/faceshape_source

   The repository contains a ``published_dataset/`` subdirectory with five
   class folders:  ``heart/``, ``oblong/``, ``oval/``, ``round/``, ``square/``.
   Each folder holds 100 JPEG images, giving 500 images total.

2. Ensure the OpenCV landmark model is present at ``data/models/lbfmodel.yaml``.
   This file is already included in the repository.

3. Run the pipeline with the ``--force-features`` flag::

       python run_project.py --force-features

   This will write ``data/processed/landmark_features.csv``.

CSV column layout
-----------------
+------------------------------+----------------------------------------------------+
| Column name                  | Description                                        |
+==============================+====================================================+
| ``label``                    | Face-shape class: heart | oblong | oval |          |
|                              | round | square                                     |
+------------------------------+----------------------------------------------------+
| ``image_path``               | Relative path to the source image file             |
+------------------------------+----------------------------------------------------+
| ``face_x``, ``face_y``       | Top-left corner of the detected face bounding box  |
| ``face_w``, ``face_h``       | Width and height of the bounding box (pixels)      |
+------------------------------+----------------------------------------------------+
| ``image_w``, ``image_h``     | Full dimensions of the source image (pixels)       |
+------------------------------+----------------------------------------------------+
| ``lm_x_00`` … ``lm_y_67``   | Normalized (x, y) coordinates for each of the 68  |
|                              | facial landmarks detected by the LBF model.        |
|                              | Coordinates are in [0, 1] relative to the face     |
|                              | bounding box (not the full image).                 |
+------------------------------+----------------------------------------------------+
| ``geom_*``                   | 16 engineered geometry features derived from the   |
|                              | raw landmark positions (see ``get_geometry_columns``|
|                              | for the full list).                                |
+------------------------------+----------------------------------------------------+
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import pandas as pd


# ---------------------------------------------------------------------------
# Default paths — relative to the project root directory
# ---------------------------------------------------------------------------

#: Default location of the pre-computed landmark feature CSV.
DEFAULT_CSV: Path = Path("data/processed/landmark_features.csv")

#: Target column used as the classification label.
LABEL_COLUMN: str = "label"

#: Ordered list of all five face-shape classes in the dataset.
CLASSES: list[str] = ["heart", "oblong", "oval", "round", "square"]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def load_features(csv_path: Optional[Path] = None) -> pd.DataFrame:
    """Load the landmark feature table from disk.

    Parameters
    ----------
    csv_path:
        Path to the CSV file.  Defaults to ``data/processed/landmark_features.csv``
        relative to the current working directory (i.e. the project root).

    Returns
    -------
    pd.DataFrame
        The full feature table.  Shape is typically (493, 160+) because 7 of
        the 500 images are dropped during landmark extraction.

    Raises
    ------
    FileNotFoundError
        If the CSV does not exist at ``csv_path``.  Run
        ``python run_project.py --force-features`` to generate it.

    Examples
    --------
    Load the table and inspect the first row::

        from src.visionaid.data_loader import load_features
        df = load_features()
        print(df.shape)      # e.g. (493, 162)
        print(df["label"].value_counts())
    """
    path = Path(csv_path) if csv_path is not None else DEFAULT_CSV
    if not path.exists():
        raise FileNotFoundError(
            f"Feature CSV not found at '{path}'.\n"
            "To generate it, run:\n"
            "    python run_project.py --force-features\n"
            "Make sure the faceshape dataset is present at "
            "data/external/faceshape_source/published_dataset/."
        )
    return pd.read_csv(path)


def get_feature_columns(df: pd.DataFrame) -> list[str]:
    """Return the names of all landmark and geometry feature columns.

    Feature columns are identified by their prefix:

    * ``lm_x_*`` / ``lm_y_*`` — normalized landmark coordinates (68 points → 136 columns).
    * ``geom_*`` — engineered geometry ratios (16 columns).

    All other columns (``label``, ``image_path``, bounding-box metadata) are excluded.

    Parameters
    ----------
    df:
        The feature table returned by :func:`load_features`.

    Returns
    -------
    list[str]
        Column names suitable for use as the ``X`` matrix in sklearn.
    """
    return [col for col in df.columns if col.startswith("lm_") or col.startswith("geom_")]


def get_geometry_columns(df: pd.DataFrame) -> list[str]:
    """Return only the engineered geometry feature columns (``geom_*``).

    These 16 features were hand-designed based on how opticians and stylists
    reason about face shape.  They encode ratios between key distances such as:

    * jaw width vs. face height
    * cheekbone width vs. jaw width
    * forehead width vs. face height
    * jaw angle (in radians)
    * left and right jaw curvature ratios

    Parameters
    ----------
    df:
        The feature table returned by :func:`load_features`.

    Returns
    -------
    list[str]
        The subset of geometry column names.
    """
    return [col for col in df.columns if col.startswith("geom_")]


def get_landmark_columns(df: pd.DataFrame) -> list[str]:
    """Return the raw normalized landmark coordinate columns (``lm_*``).

    There are 68 landmarks × 2 coordinates (x, y) = 136 columns in total.
    Landmark numbering follows the standard 68-point iBUG convention used by
    the OpenCV LBF facemark model.

    Parameters
    ----------
    df:
        The feature table returned by :func:`load_features`.

    Returns
    -------
    list[str]
        The 136 landmark coordinate column names.
    """
    return [col for col in df.columns if col.startswith("lm_")]


def dataset_summary(df: pd.DataFrame) -> None:
    """Print a concise summary of the feature table to stdout.

    Useful for a quick sanity check after loading the CSV.

    Parameters
    ----------
    df:
        The feature table returned by :func:`load_features`.

    Examples
    --------
    ::

        from src.visionaid.data_loader import load_features, dataset_summary
        df = load_features()
        dataset_summary(df)
    """
    feature_cols = get_feature_columns(df)
    geom_cols = get_geometry_columns(df)
    lm_cols = get_landmark_columns(df)

    print("=" * 50)
    print("VisionAid landmark feature dataset")
    print("=" * 50)
    print(f"Total samples (rows): {len(df)}")
    print(f"Total columns:        {df.shape[1]}")
    print()
    print("Classes:")
    for cls, count in df[LABEL_COLUMN].value_counts().sort_index().items():
        print(f"  {cls:<10} {count:>4} images")
    print()
    print(f"Feature columns: {len(feature_cols)}")
    print(f"  Landmark coordinates : {len(lm_cols)} (68 points × 2)")
    print(f"  Geometry features    : {len(geom_cols)}")
    print()
    print("Geometry feature names:")
    for col in geom_cols:
        print(f"  {col}")
    print("=" * 50)
